image_root: 'datasets/vision/coco/'
ann_root: 'annotation'
dataset: 'coco'

# set pretrained as a file path or an url
pretrained: 'pretrained/model_base_retrieval_coco.pth'

# size of vit model; base or large

vit: 'base'
batch_size_train: 32
batch_size_test: 32
vit_grad_ckpt: False
vit_ckpt_layer: 4
init_lr: 1e-7

sd_dim: 768
sd_num: 100

# vit: 'large'
# batch_size_train: 16
# batch_size_test: 32
# vit_grad_ckpt: True
# vit_ckpt_layer: 12
# init_lr: 5e-6

image_size: 384
queue_size: 57600
alpha: 0.4
k_test: 256
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 5
