image_root: 'datasets/vision/flickr/'
ann_root: 'annotation'
dataset: 'flickr'

# set pretrained as a file path or an url
pretrained: 'pretrained/clip_large_retrieval_flickr.pth'

init_lr: 1e-5
batch_size_train: 16
batch_size_test: 32

sd_dim: 768
sd_num: 100

image_size: 336
queue_size: 57600
alpha: 0.4

# optimizer
weight_decay: 0.2
min_lr: 0
max_epoch: 10


